import Content from "@components/Content"
import Sidebar from "@components/Sidebar"
import Head from "next/head"

export default function Create() {
    return (
        <div>
            <Head>
                <title>Add Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col">
                <main className="flex">
                    <Sidebar />
                    <section className="basis-4/5">
                        <Content>
                            <div className="my-6 mt-16 px-6">
                                <p className="text-white text-3xl font-bold">Add Product</p>
                                <div className="bg-white rounded-2xl p-4 my-6 flex flex-col space-y-4">
                                    <form className="p-6 flex flex-col space-y-4">
                                        <div className="flex">
                                            <label className="font-medium basis-1/5">Category</label>
                                            <select className="rounded-xl bg-white p-2 basis-4/5 border focus:outline-none">
                                                <option disabled selected>-- Choose --</option>
                                            </select>
                                        </div>
                                        <div className="flex">
                                            <label className="font-medium basis-1/5">Product Name</label>
                                            <input type="text" className="rounded-xl bg-white p-2 basis-4/5 border focus:outline-none" />
                                        </div>
                                        <div className="flex">
                                            <label className="font-medium basis-1/5">Description</label>
                                            <textarea className="rounded-xl bg-white p-2 basis-4/5 border focus:outline-none"></textarea>
                                        </div>
                                        <div className="flex">
                                            <div className="basis-1/5"></div>
                                            <div className="basis-4/5">
                                                <button type="submit" className="text-white font-semibold w-32 text-center bg-violet-500 rounded-xl shadow hover:bg-violet-600 p-2">Save</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </Content>
                    </section>
                </main>
            </div>
        </div>
    )
}