/* eslint-disable react/jsx-key */
import Content from "@components/Content"
import Sidebar from "@components/Sidebar"
import Head from "next/head"
import Link from "next/link"
import React from "react"
import { FaPlus } from "react-icons/fa"
import { useTable } from "react-table"

export default function Index() {
    const data = React.useMemo(() => [
        {
            name: 'Fihi Ma fihi',
            author: 'Jalaludin Rumi'
        },
        {
            name: 'Fihi Ma fihi',
            author: 'Jalaludin Rumi'
        }
    ], [])

    const columns = React.useMemo(() => [
        {
            Header: 'Name',
            accessor: 'name'
        },
        {
            Header: 'Author',
            accessor: 'author'
        }
    ], [])

    const tableInstance = useTable({ columns, data })

    const { getTableProps, getTableBodyProps, headerGroups, rows, prepareRow } = tableInstance

    return (
        <div>
            <Head>
                <title>Product</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col">
                <main className="flex">
                    <Sidebar />
                    <section className="basis-4/5">
                        <Content>
                            <div className="my-6 mt-16 px-6">
                                <p className="text-white text-3xl font-bold">Product</p>
                                <div className="bg-white rounded-2xl p-4 my-6 flex flex-col space-y-4">
                                    <Link href="/b/product/create">
                                        <a className="flex w-32 bg-emerald-400 rounded-2xl hover:bg-emerald-500 py-2 justify-center text-xs items-center text-white font-medium">
                                            <FaPlus />
                                            Add Product
                                        </a>
                                    </Link>
                                    <table {...getTableProps()} className="w-full text-left">
                                        <thead>
                                            {headerGroups.map(headerGroup => (
                                                <tr {...headerGroup.getHeaderGroupProps()}>
                                                    {headerGroup.headers.map(column => (
                                                        <th
                                                            {...column.getHeaderProps()}
                                                            className="p-2 bg-teal-100"
                                                        >
                                                            {column.render('Header')}
                                                        </th>
                                                    ))}
                                                </tr>
                                            ))}
                                        </thead>
                                        <tbody {...getTableBodyProps()} className="border">
                                            {rows.map(row => {
                                                prepareRow(row)
                                                return (
                                                    <tr {...row.getRowProps()}>
                                                        {row.cells.map(cell => {
                                                            return (
                                                                <td
                                                                    {...cell.getCellProps()}
                                                                    className="p-2 border"
                                                                >
                                                                    {cell.render('Cell')}
                                                                </td>
                                                            )
                                                        })}
                                                    </tr>
                                                )
                                            })}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </Content>
                    </section>
                </main>
            </div>
        </div>
    )
}