version: '3'
services:
  frontend: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore-fe
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    networks:
      - bookstore

networks:
  bookstore:
    external: true