import Head from "next/head";
import Sidebar from "@components/Sidebar";
import Topbar from "@components/Topbar";
import DashboardCard from "@components/DashboardCard";
import Content from "@components/Content";

export default function Index() {
    return (
        <div>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="flex flex-col">
                <main className="flex">
                    <Sidebar />
                    <section className="basis-4/5">
                        <Content>
                            <DashboardCard />
                        </Content>
                        <div className="bg-gray-200">

                        </div>
                    </section>
                </main>

                <footer>
                </footer>
            </div>
        </div>
    )
}