import Head from 'next/head'
import Image from 'next/image'
import Navbar from '@components/Navbar'
import Banner from '@components/Banner'
import Featured from '@components/Featured'
import Footer from '@components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className='container mx-auto max-w-6xl'>
        <Banner />
        <Featured />
      </main>

      <hr />
      <footer className="container mx-auto max-w-6xl mt-4 md:mt-8">
        <Footer />
      </footer>
    </div>
  )
}
