import Head from 'next/head'
import Image from 'next/image'
import Navbar from '@components/Navbar'
import Banner from '@components/Banner'
import Featured from '@components/Featured'
import Footer from '@components/Footer'
import Popular from '@components/Popular'
import { useState } from 'react'
import Login from '@components/Login'

export default function Home() {

  const [modalLogin, setModalLogin] = useState(false)

  const toggleModalLogin = () => {
    setModalLogin(!modalLogin)
  }

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar showLogin={toggleModalLogin} />

      <Login modal={modalLogin} closeModal={toggleModalLogin} />
      <main className='container mx-auto max-w-6xl mt-[4.1rem] md:mt-[5.2rem] lg:mt-24'>
        <Banner />
        <Featured />
        <Popular />
      </main>

      <hr />
      <footer className="container mx-auto max-w-6xl px-4 lg:px-0">
        <Footer />
      </footer>
    </div>
  )
}
