import Head from 'next/head'
import Navbar from '@components/Navbar'
import Banner from '@components/Banner'
import Featured from '@components/Featured'
import Footer from '@components/Footer'
import { useState } from 'react'
import Login from '@components/Login'

export default function Wrapper(props) {

    const [modalLogin, setModalLogin] = useState(false)

    const toggleModalLogin = () => {
        setModalLogin(!modalLogin)
    }

    return (
        <div className='bg-gray-50'>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar showLogin={toggleModalLogin} />

            <Login modal={modalLogin} closeModal={toggleModalLogin} />
            <main className='container mx-auto max-w-5xl px-4 lg:px-0 pt-[4.1rem] md:pt-[5.2rem] lg:pt-20'>
                {props.children}
            </main>

            <hr />
            <footer className="container mx-auto max-w-5xl px-4 lg:px-0">
                <Footer />
            </footer>
        </div>
    )
}
